site_name: RFT – Resonanzfeldtheorie
site_url: https://da-Franze.github.io/RFT-Physik-Projekt/
repo_url: https://github.com/da-Franze/RFT-Physik-Projekt
repo_name: RFT-Physik-Projekt

# Wir arbeiten direkt aus dem Repo-Root, damit de/… und en/… ohne Umbau funktionieren.
docs_dir: .

theme:
  name: material

# README.md als Startseite – kein index.md nötig.
nav:
  - Home: README.md
  - Deutsch:
      - Überblick: de/README.md
      - Fortgeschritten:
          - Supraleitung (RFT_48): de/docs/fortgeschritten/RFT_48_Supraleitung.md
  - English:
      - Overview: en/README.md
      # Weitere EN-Seiten kannst du hier schrittweise ergänzen.

# Bis alles verlinkt ist, bricht der Build nicht wegen toter Links ab.
strict: false

# (Optional sinnvoll, aber unkritisch) gängige Markdown-Extras:
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - footnotes
  - attr_list
