site_name: RFT – Resonanzfeldtheorie
site_url: https://da-franze.github.io/RFT-Physik-Projekt/
repo_url: https://github.com/da-Franze/RFT-Physik-Projekt
repo_name: RFT-Physik-Projekt

# WICHTIG: wir lassen das Repo-Root scannen, verlinken aber NUR das,
# was in 'nav' steht. .github/ etc. werden nicht eingebunden.
docs_dir: .

theme:
  name: material

nav:
  - Start (DE): de/docs/index.md
  - Deutsch:
      - Übersicht: de/docs/index.md
      # Beispiel – bitte anpassen/erweitern:
      - Supraleitung (RFT_48): de/docs/fortgeschritten/RFT_48_Supraleitung.md
      # ...weitere deutsche Seiten hier...
  - English:
      - Home (EN): en/docs/index.md
      # ...weitere englische Seiten hier...

# (Optional) Markdown-Extras
markdown_extensions:
  - admonition
  - toc:
      permalink: true

# Ausgabeordner (Standard wäre 'site')
site_dir: site
