site_name: RFT – Resonanzfeldtheorie
site_url: https://da-Franze.github.io/RFT-Physik-Projekt/
repo_url: https://github.com/da-Franze/RFT-Physik-Projekt
repo_name: RFT-Physik-Projekt

# Wichtig: MkDocs sucht standardmäßig in "docs/"
# Wir verlinken Dateien außerhalb von docs/ nur explizit in der nav.
docs_dir: docs

theme:
  name: material

nav:
  - Home: index.md
  - Deutsch:
      - Überblick: ../de/README.md
  - English:
      - Overview: ../en/README.md

# Erst mal robust bauen: Fehlende Links sollen den Build NICHT abbrechen.
strict: false
