site_name: RFT – Resonanzfeldtheorie
site_url: https://da-franze.github.io/RFT-Physik-Projekt/
repo_url: https://github.com/da-Franze/RFT-Physik-Projekt
repo_name: RFT-Physik-Projekt

# Aus dem Repo-Root bauen – passt zu deiner Struktur
docs_dir: .

theme:
  name: material

# Nur Pfade, die im Screenshot eindeutig vorhanden sind (keine abgeschnittenen Namen!)
nav:
  - Home: README.md
  - Deutsch:
      - Überblick: de/README.md
      - Einstieg:
          - Übersicht: de/index.md
          - Für Neugierige: de/einstieg/neugierige.md
          - Für Physiker: de/einstieg/physiker.md
          - Für Philosophen: de/einstieg/philosophen.md
      - Anwendungen:
          - Status: de/docs/anwendungen/IN_ARBEIT.md
      - Spezialisierung:
          - Status: de/docs/spezialisierung/IN_ARBEIT.md
      - Fortgeschritten:
          - Supraleitung (RFT_48): de/docs/fortgeschritten/RFT_48_Supraleitung.md
      - Autor: de/autor.md
      - Kontakt: de/kontakt.md
      - Mitwirken: de/mitwirken.md
  - English:
      - Overview: en/README.md
      - Entry:
          - Curious: en/entry/curious.md
          - Physicists: en/entry/physicists.md
          - Philosophers: en/entry/philosophers.md
      - Applications:
          - Status: en/docs/applications/IN_WORK.md
      - Specialization:
          - Index: en/docs/specialization/index.md
          - Status: en/docs/specialization/IN_WORK.md
          - Notes: en/docs/specialization/under_construction.md
      - Advanced:
          - Status: en/docs/advanced/IN_WORK.md
      - Author: en/author.md
      - Contact: en/contact.md
      - Contribute: en/contribute.md

# Nicht wegen Kleinigkeiten abbrechen, solange wir die Nav schrittweise erweitern
strict: false

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - footnotes
  - attr_list
