# RFT_v3_Glossar_DE — Resonanzfeldtheorie: Begriffslexikon
## Version: 2.0 | Datum: 09.05.2026 | Instanz: T-Glossar
## Autorisiert: Franz Zollner | Protokoll: Multi-Instanz v6.1
## Änderungen v1.0→v2.0: Leserführung ergänzt; 5 neue Einträge (DC v10.15);
##   "Gemeinsame Resonanz-Mode" kanonisch; Verworfene Begriffe erweitert;
##   DC-Referenz aktualisiert auf v10.15

---

> **Methodischer Grundsatz:**
> Konzepte und Definitionen stammen von Franz Zollner.
> Die Verschriftlichung erfolgt durch KI-Instanzen — alle Einträge
> gegen die v3-Serie verifiziert. Primärquelle ist jeweils angegeben.
>
> **Hierarchie der Wahrheit:**
> Franz direkte Aussage → DC v10.15 → v3-Final → v2-Serie → KI-Content
>
> **Konfidenz-Marker:**
> ✓ HOCH — rigoros hergeleitet oder von Franz bestätigt
> ○ MITTEL — konzeptuell konsistent, formal noch offen
> ⚠️ NIEDRIG / SPEKULATIV — Arbeitshypothese
> 🚩 OFFEN — aktives Forschungsproblem

---

## Leserführung (für Physiker ohne RFT-Vorwissen)

Die Resonanzfeldtheorie (RFT) beschreibt Raum, Zeit und Materie als Emergenzphänomene eines einzigen dynamischen Resonanzmediums — der **Dynamischen Resonanz-Raummatrix (DRM)**. Dieses Lexikon gibt präzise Definitionen der RFT-spezifischen Terminologie mit explizitem Vergleich zur Standard-Physik, wo die Konzepte abweichen.

**Wesentliche Begriffsunterschiede zur Standard-Physik:**

| Standard-Physik | RFT | Status |
|----------------|-----|--------|
| Vakuum = leerer Raum | DRM = aktives Resonanzmedium | ✓ HOCH |
| Masse = fundamentale Eigenschaft (Higgs) | Masse = emergentes Label für lokale κ-Dichte | ✓ HOCH |
| Teilchen = punktförmig | Teilchen = topologischer Wirbel in der DRM | ✓ HOCH |
| Zeit = fundamentale Dimension | Zeit = emergente Schwebungsfrequenz von DRM-Moden | ✓ HOCH |
| Feinstrukturkonstante α = empirisch | α = reine π-Geometrie (keine freien Parameter) | ✓ HOCH |
| Äquivalenzprinzip = Postulat | Äquivalenzprinzip = geometrische Konsequenz | ✓ HOCH |
| Gravitationswellen = Raumzeitkräuselung | GW = longitudinale Mode der DRM | ✓ HOCH |

---

## Warnungen (vor Nutzung lesen!)

```
❌ "Raumgitter"            → FALSCH (weckt Kristallgitter-Assoziation)
                              KORREKT: "Raummatrix" oder "DRM"
❌ "Raumresonanz-Matrix"   → FALSCH (von Franz explizit abgelehnt)
❌ "Master-String"         → v2-Artefakt, nicht v3-kanonisch
❌ c₀                      → veraltet; korrekt: c
❌ ħ als fundamental       → ħ ist algebraische Identität in v3
❌ AP als geomet. Punkt    → AP = Dimensionskopplung! (Franz, 15.03.2026)
❌ 0.67 ppm Residuum α     → falsch; korrekt: 2.22 ppm
❌ 4:1 Frequenzverhältnis (verallgemeinert) → kontextabhängig; siehe "Kalte Kondensation"
❌ ART-Sprache in RFT      → Metrik, Geodäten, Tensor-Sprache vermeiden
❌ "Topologische Identität" → VERALTET; korrekt: "Gemeinsame Resonanz-Mode" (v10.15)
```

---

## A

### Ankerpunkt (AP) — Anchor Point
**EN:** anchor point (AP)
**Konfidenz:** ✓ HOCH (Kerndefinition); ○ MITTEL (Dimensionskopplung)
**Primärquelle:** KORREKTUR_RFT_005_Ankerpunkte.md; Franz 15.03.2026

Ein Ankerpunkt ist die **Verankerung eines Wirbels in der Raummatrix** — die Kopplungsstelle, über die Wirbel miteinander in Interaktion treten. Ein AP ist nicht notwendigerweise ein geometrischer Punkt; er kann ein Punkt, eine Fläche, eine Linie oder eine andere geometrische Einheit sein.

**AP als Dimensionskopplung (○ MITTEL, Franz 15.03.2026):**
In einem Lorentz-Feld ohne ausgezeichnete Richtung koppelt ein AP an einen dimensionalen Freiheitsgrad der Raummatrix: n AP = Kopplung an n Dimensionen.

Hinweis: Der AP ist **nicht** analog zu einem klassischen Feldknoten oder Gitterpunkt. Er repräsentiert eine topologische Kopplung, keinen räumlichen Ort.

**Kanonische AP-Tabelle:**

| Teilchen | AP | Spin | Konfidenz |
|----------|----|------|-----------|
| Elektron e⁻ | 1 | ½ | ✓ HOCH |
| Positron e⁺ | 1 | ½ | ✓ HOCH |
| Photon γ | 2 | 1 | ✓ HOCH (Franz, 11.03.2026) |
| Quark (d/u/s/...) | 3 | ½ | ✓ HOCH |
| Proton | 9 | ½ | ✓ HOCH (3 Quarks × 3 AP) |
| Delta-Baryon | 9 | 3/2 | ✓ HOCH |
| Neutrino ν | 0 | ½ | ⚠️ Arbeitshyp. |

**Konsequenz:** Leptonen (1 AP) koppeln nur an 1 Dimension → keine Farbladung. Das ist eine geometrische Konsequenz, kein Postulat.

---

### Ankerpunkt-Hierarchie — Anchor Point Stability Hierarchy
**EN:** anchor point stability hierarchy
**Konfidenz:** ✓ HOCH
**Primärquelle:** KORREKTUR_RFT_005_Ankerpunkte.md; v3_011 Final v1.0

Stabilitätshierarchie topologischer Strukturen nach AP-Zahl:
- 1 AP: instabil (kann nicht frei existieren)
- 2 AP: kurzlebig (Mesonen, transiente Zustände; Photon stabil während Propagation)
- 3 AP: stabil (Quarks — koppeln an alle 3 Raumdimensionen → Confinement)
- ≥ 3 AP: makroskopische Stabilität

**Resonanzbedingung:** n_AP ≥ n_dim = 3 (in 3D) für stabile isolierte Strukturen.

---

## D

### Dispersionsrelation — Dispersion Relation
**EN:** dispersion relation
**Konfidenz:** ✓ HOCH
**Primärquelle:** RFT_v3_004, Kap. 2.2; RFT_v3_001, Kap. 2

Fundamentale Relation zwischen Kreisfrequenz ω und Wellenzahl k im DRM, die direkt aus der linearisierten Master-Gleichung folgt:

```
ω² = c²(k² + κ²)
```

Mit ħ multipliziert: E² = (pc)² + (m_eff c²)²
(Einstein-Energie-Impuls-Relation emergiert als Grenzfall — sie wird nicht postuliert.)

Physikalische Bedeutung: κ ≠ 0 → Resonanzstruktur hat eine Eigenfrequenz → effektive Masse. κ = 0 → Photon-artiges Propagieren (masseloses Ausbreiten).

---

### DRM — Dynamische Resonanz-Raummatrix
**Vollname:** Dynamische Resonanz-Raummatrix
**EN:** Dynamic Resonance Matrix (DRM)
**Konfidenz:** ✓ HOCH
**Primärquelle:** RFT_v3_001, Kap. 1.1

Abkürzung für das Trägermedium der RFT. DRM ist korrekt und kein KI-Artefakt. Synonyme Bezeichnungen: "Raummatrix" (bevorzugt in Fließtext), "DRM" (technisch, bei Formeln).

→ Siehe: **Raummatrix**

---

## F

### Feinstrukturkonstante α — Fine Structure Constant
**EN:** fine structure constant
**Konfidenz:** ✓ HOCH
**Primärquelle:** RFT_v3_002; RFT_v3_001, Kap. 4; RFT_v3_005

In der RFT folgt α aus reiner π-Geometrie der DRM ohne freie Parameter:

```
α⁻¹ = 4π³ + π² + π = 137.036 304...
```

Residuum gegenüber CODATA 2018: **2.22 ppm** (⚠️ NIEMALS 0.67 ppm verwenden — bekanntes KI-Artefakt!).

| Term | Wert | Geometrische Bedeutung |
|------|------|------------------------|
| 4π³ | 124.025... | 3D-Volumen (sphärischer k-Raum; 4 Kugeln = Tetraeder) |
| π² | 9.870... | 2D-Fläche (sphärische Harmonische) |
| π | 3.142... | 1D-Länge (Spinachse) |

Physikalische Bedeutung: α misst die kritische Modenanzahl N_krit — wie viele Freiheitsgrade eine sphärische Resonanz auf dem kubischen DRM besetzen muss, um stabil zu sein. Dies folgt aus der Triangulations-Logik (→ **Triangulations-Logik**).

Die 2.22 ppm-Abweichung ist eine offene Frage (fehlender Korrekturterm? Zeitpfeil-Signatur? Strukturmerkmal?).

---

### Flussfaktor Φ — Flux Factor
**EN:** flux factor
**Formel:** Φ = 2α/(1+α²) ≈ 0.014 596
**Konfidenz:** ✓ HOCH (kanonisch)
**Primärquelle:** RFT_v3_002; RFT_v3_006

Φ beschreibt die relative Phasenasymmetrie der zwei Grundmoden der DRM. Φ ≠ 0 treibt den Zeitpfeil über gerichtete Schwebungsfrequenz an (→ **Schwebung**, **Zeitmotor**).

Verwendung: G·m/c² = L²/(4π·Φ) (Gravitationsformel, dimensional korrekt); Φ_total = Φ_mat + Φ_fil (Kosmologie, v3_010).

**Achtung Symbolkonflikt:**
- ε = geometrischer Winkelversatz der DRM-Achsen von der 90°-Orthogonalität (qualitativ; Wert ≈ Φ via Umlaufmodell ○ HOCH)
- δ ≈ 2α ≈ 0.0146 rad (temporale Phasenasymmetrie aus v3_001)
- Φ = 2α/(1+α²) ≈ 0.01459 (kanonischer Quantitativausdruck)
→ Diese drei Symbole NIEMALS verwechseln!

---

### Führungsfeld — Pilot Field / Guidance Field
**EN:** pilot field; guidance field
**Konfidenz:** ✓ HOCH (Konzept); ○ MITTEL (formale Details)
**Primärquelle:** RFT_v3_011, Teil 3

In der RFT-Interpretation der Quantenmechanik besteht jede physikalische Konfiguration aus zwei Komponenten:

1. **Vortex-Kern:** die topologische Wirbelstruktur (das eigentliche "Teilchen")
2. **Führungsfeld (Ψ_Feld):** das ausgedehnte Resonanzfeld, das den Kern deterministisch führt

Das Führungsfeld ist physikalisch real — es ist kein mathematisches Hilfskonstrukt wie in Bohms Pilotwellen-Interpretation. Es emergiert als Lösung der Master-Gleichung. Der Vortex-Kern folgt dem Gradienten des effektiven Potentials:

```
V_eff = −½c²·α_K·|Ψ_Feld|²
F = −∇V_eff   (deterministisch!)
```

**Unterschied zu Bohm:** Bohm's Führungswelle ist mathematisch definiert als Q = −ħ²∇²R/(2mR). Das RFT-Führungsfeld ist die physikalische Raummatrix-Modulation selbst — eine reale physikalische Größe, kein mathematisches Konstrukt.

α_K = Kern-Kopplungsstärke (≠ Feinstrukturkonstante α!)

---

## G

### Gemeinsame Resonanz-Mode — Shared Resonance Mode
**EN:** shared resonance mode
**Konfidenz:** ✓ HOCH (Franz, 05.04.2026)
**Primärquelle:** RFT_v3_017 (Verschränkung); DC v10.15
**⚠️ NEU v2.0: ersetzt den veralteten Begriff "Topologische Identität"**

Zwei physikalische Objekte teilen eine **Gemeinsame Resonanz-Mode**, wenn ihr kombinierter Zustand Ψ(x₁, x₂) nicht als Produkt faktorisierbar ist:

```
Ψ(x₁, x₂) ≠ Ψ₁(x₁) · Ψ₂(x₂)
```

Das ist die RFT-Erklärung der Quantenverschränkung: Es gibt keine nicht-lokale "spukhafte Fernwirkung" — beide Objekte sind schlicht **Ausprägungen derselben Raummatrix-Mode**. Die Nicht-Separierbarkeit folgt aus dem λ-Term der Master-Gleichung (Nicht-Linearität erzwingt Modenkopplung).

**Wichtiger Terminologiehinweis:**
```
VERALTET: "Topologische Identität"  → NICHT mehr verwenden!
KORREKT:  "Gemeinsame Resonanz-Mode"
```
"Topologische Identität" war missverständlich, weil es eine Eigenschaft der Topologie suggeriert, während die eigentliche Ursache der λ-Term (Nicht-Linearität) ist.

**Kanonisch seit:** DC v10.15 (Franz, 05.04.2026).

---

### Gravitation (RFT)
**EN:** gravitation (emergent from spin delay)
**Konfidenz:** ✓ HOCH
**Primärquelle:** RFT_v3_003, Kap. 1–3

In der RFT ist Gravitation kein fundamentales Axiom, sondern eine emergente Eigenschaft der DRM:

- **G·m** ist eine topologische Grundgröße [m³/s²] — nicht das Produkt zweier unabhängiger Größen.
- **[kg]** ist kein Naturgesetz, sondern ein Label für die gravitationale Schleppwirbelstärke.
- **Mechanismus:** Jeder massive Vortex mit Spin erzeugt eine Phasenverzögerung τ_lag → longitudinale Verspannung der Raummatrix → Gravitation.

**Gravitation = longitudinale Kompressionsmode** der Raummatrix (im Gegensatz zu EM = torsionale Mode).

Zwei G-Mechanismen:
- G_elementar: Quark-Fehlanpassung (lokale Verspannung)
- G_hadron = 4π · G_elementar: Farbladungs-Aufrichtung (sphärische Kopplung)

Hinweis: Gravitation in der RFT ist konzeptuell ähnlich, aber mechanisch verschieden von der ART-Raumzeitkrümmung. Die ART bleibt eine korrekte effektive Feldtheorie; die RFT liefert ihr mechanisches Substrat.

---

## I

### Innensicht-Prinzip — Inside-View Principle
**EN:** inside-view principle
**Konfidenz:** ✓ HOCH
**Primärquelle:** RFT_v3_001, Kap. 1.1

Das Resonanzfeld ist nicht *im* Raum — es *ist* der Raum selbst. Alle Beobachter sind Teil des Feldes. Es gibt kein "Außen" und kein absolutes Bezugssystem. Die Spezielle Relativitätstheorie emergiert als Konsequenz: Alle Beobachter innerhalb des Feldes messen dieselbe Ausbreitungsgeschwindigkeit c.

Dies ist keine Äthertheorie. Ein klassischer Äther ist ein Medium *im* Raum mit absolutem Ruhesystem. In der RFT *ist* das dynamische Resonanzfeld der Raum — es gibt kein Äußeres.

Konsequenz: Aussagen über den Zustand *vor* der Raummatrix (Proto-Zustand) sind von innen prinzipiell unmöglich (→ Domain L, offene Spekulation).

---

## K

### Kalte Kondensation — Cold Condensation
**EN:** cold condensation
**Konfidenz:** ○ MITTEL (Kernmechanismus); ⚠️ NIEDRIG (quantitative Details)
**Primärquelle:** RFT_v3_009, Final v1.1

Bildung geordneter Materie-Strukturen aus dem RFT-Urfeld ohne Abkühlungsprozess im thermodynamischen Sinne. "Kalt" bezeichnet nicht eine niedrige Temperatur, sondern das Fehlen eines externen Kühlprozesses: Ordnung entsteht durch **Resonanzqualität** (Q-Faktor), nicht durch Wärmeabgabe.

Schlüsselmechanismus: Wenn Q > Q_krit1 ~ 10³ (Hypothese), kondensieren Resonanzen spontan zu stabilen Vortex-Strukturen. Antimaterie wird dabei **komplementär gebunden** (nicht "vernichtet" oder "verschwunden").

**Zwei kanonische Verhältnisse — NICHT verwechseln (Franz, 24.03.2026):**
```
3:1 = Raummatrix-Generierung:
      Spin −1 (Antimaterie) : Spin +1/3 (Quark)
      → Verhältnis der Spin-Beiträge bei der Matrixkonstitution ✓ HOCH

4:1 = Materie-Kondensation:
      Separater Prozess! Verhältnis im Kondensationsschritt selbst
      ○ MITTEL (Franz, 24.03.2026)
```
⚠️ "4:1" ist NICHT generell falsch — es beschreibt einen anderen Prozess als 3:1. Der historische Fehler war die Verwechslung beider Prozesse.

---

### κ — Resonanz-Steifigkeit — Resonance Rigidity
**EN:** resonance rigidity; resonance stiffness
**Konfidenz:** ✓ HOCH (Primärstatus); ○ MITTEL (quantitative Herleitung)
**Primärquelle:** RFT_v3_001, Kap. 2.2 + 3.3

κ ist die **Primärgröße** der RFT — die natürliche Wellenzahl des Vakuums, die Steifigkeit des Resonanzmediums gegen Deformation.

```
κ = 1/L₀ ≈ 1.91/l_P ≈ 1.18×10³⁵ m⁻¹
```

**Kausale Richtung (entscheidend):**
- In QFT: Masse ist Input → erzeugt den –(mc/ħ)²Ψ-Term
- In RFT: κ ist Matrixeigenschaft (aus Geometrie) → erzeugt was wir "Masse" nennen

Effektive Masse: m_eff = ħκ/c

κ ist NICHT der "Masseterm" — es ist die Resonanz-Steifigkeit des Mediums. Masse ist das emergente Label. Diese Umkehrung der Kausalrichtung ist fundamental für das RFT-Paradigma.

---

### Kompression — Compression
**EN:** compression (longitudinal mode)
**Konfidenz:** ✓ HOCH
**Primärquelle:** RFT_v3_012, Kap. 3; RFT_v3_003, Kap. 3

Longitudinale Deformationsmode der Raummatrix entlang der Ausbreitungsrichtung. In der RFT entspricht diese Mode:
- **Trägheitsmasse m_i:** lokale Kompression des κ-Feldes um einen Vortex (statisch, instantan)
- **Elektrisches Feld E:** longitudinale Kompressionsmode bei EM-Wechselwirkung
- **Gravitation:** longitudinale Spinverzug-Mode des Schleppwirbels

Vergleich mit Torsion → siehe: **Torsion**

---

## L

### L₀ — Fundamentale Matrixlänge
**EN:** fundamental matrix length; matrix cell size
**Formel:** L₀ = (π/6)·l_P ≈ 0.5236·l_P
**Konfidenz:** ✓ HOCH
**Primärquelle:** RFT_v3_001, Kap. 5; RFT_v3_005, Kap. 1.2

Die fundamentale Längenskala der DRM, hergeleitet aus dem **Kugel-im-Würfel-Volumen-Verhältnis**:

```
V(Kugel, r) / V(Würfel, 2r) = (4/3)πr³ / 8r³ = π/6
→ L₀ = (π/6)·l_P
```

π/6 ist die Effizienz, mit der eine sphärische Resonanz den kubischen Matrixraum füllt. Dies ist keine Approximation und kein Fit-Parameter.

**Primärdefinition (ħ-frei!):**
```
L₀ = 1/κ  ← PRIMÄRDEFINITION
L₀ = (π/6)·l_P  [numerische Verifikation, nicht Definition]
```

🚩 **ħ-Zirkularität (höchste Priorität, gesamtes Projekt):**
L₀ = (π/6)·l_P enthält l_P = √(ħG/c³) → enthält ħ → G·ħ-Identität ist algebraisch, keine unabhängige Herleitung. L₀ ohne ħ als Input zu bestimmen ist das offene Kernproblem.

**Geometrische Deutung (Franz, 25.03.2026) ✓ HOCH:**
```
l_P = Raumdiagonale des Matrixwürfels (alle 3 Dimensionen)
L₀  = Seite a des Würfels (minimale Einheit)
→ L₀ < l_P  ✓
```

---

## M

### Master-Gleichung — Master Equation
**EN:** master equation
**Konfidenz:** ✓ HOCH
**Primärquelle:** RFT_v3_001, Kap. 2

Die fundamentale Feldgleichung der gesamten RFT. Alle Physik der RFT emergiert aus ihr:

```
∂²Ψ/∂t² = c²∇²Ψ − γ∂Ψ/∂t − c²κ²Ψ + λ|Ψ|²Ψ + η
```

| Term | Symbol | Bedeutung |
|------|--------|-----------|
| Wellenausbreitung | c²∇²Ψ | Propagation mit Lichtgeschwindigkeit |
| Dämpfung/Zeitpfeil | −γ∂Ψ/∂t | Irreversibilität, Q-Faktor, Zeitpfeil |
| Resonanz-Steifigkeit | −c²κ²Ψ | Primärgröße; erzeugt effektive Masse |
| Nichtlinearität | +λ\|Ψ\|²Ψ | Stabilisiert Solitone (Teilchen) |
| Selbstwechselwirkung | η | Vakuumfluktuationen (η=0 im Grundzustand) |

Ψ ist nicht ein Feld *im* Raum, sondern das Feld, dessen dynamischer Grundzustand den Raum selbst konstituiert.

---

### Modensprung — Mode Transition
**EN:** mode transition
**Konfidenz:** ✓ HOCH (Konzept); ○ MITTEL (quantitative Schwellwerte)
**Primärquelle:** RFT_v3_008, Draft v1.2

Diskreter Übergang zwischen verschiedenen Resonanzzuständen der DRM beim Überschreiten einer kritischen Knotendichte. Anders als kontinuierliche Übergänge in der ART:

```
Mode 0:  Q ≈ 1        — Ur-Chaos / kein Raum (NICHT "Vakuum"!)
Mode 1:  Q > Q_krit1  — geordnete Raummatrix (normaler Raum)
Mode 2:  Q ≫ Q_krit2  — Schwarzes Loch (λ₂ ≈ λ₁/2, andere Zeitrate)
```

⚠️ Mode 0 ist KEIN Vakuum — es ist der Zustand vor der Raummatrix-Konstitution. "Ur-Chaos" oder "kein Raum" sind korrekte Bezeichnungen.

Verschiedene Moden haben verschiedene Φ-Werte → verschiedene Zeitraten (Φ₂ ≠ Φ₁).

---

## N

### Neutrino (RFT-Interpretation)
**EN:** neutrino (RFT interpretation)
**Konfidenz:** ○ MITTEL (Longitudinalwellen-Hypothese, Franz 15.03.2026)
**Primärquelle:** DC v10.4, Domain G + I; RFT_v3_014, Final v1.0

In der RFT-Arbeitshypothese ist das Neutrino keine Wirbelstruktur mit Ankerpunkten, sondern eine **longitudinale Welle der Raummatrix** (0 AP):

```
Neutrino: longitudinale Welle, κ > 0 → m_ν winzig (≠ 0) ✓
GW:       longitudinale Welle, κ ≈ 0 → m ≈ 0
```

Beide sind longitudinale Moden desselben Trägermediums; der Unterschied liegt in der "inneren Dichte" κ der Welle:
- Gravitationswellen ~ Radiowellen (geringe innere Dichte, κ ≈ 0)
- Neutrinos ~ Röntgenstrahlung (hohe innere Dichte, κ > 0)

**RFT-Vorhersage:** Beide propagieren mit c im Vakuum — konsistent mit SN 1987A (gleichzeitige Ankunft von Neutrinos und Gravitationswellen) ○ MITTEL.

**Verbleibende Spannung:** 0-AP-Beschreibung (→ masselös) widerspricht beobachteten Neutrino-Oszillationen (→ m_ν > 0). Kandidat-Auflösung: kleine Kopplung, nicht exakt 0-AP. 🚩 Offen.

---

## P

### Photon (RFT)
**EN:** photon (RFT description)
**Konfidenz:** ✓ HOCH (Franz, 11.03.2026)
**Primärquelle:** RFT_v3_012, Final v1.3.1; DC v10.4

**Status ENTSCHIEDEN (Franz, 11.03.2026):**

Das Photon ist eine stabile propagierende Welle bestehend aus:
- **e⁻ (1 AP) + e⁺ (1 AP) = 2 AP total**
- Spin 1 (Triplett-Konfiguration: ↑↑)
- n = 0 in der Modenklassifikation (komplementäre Beschreibung, kein Widerspruch)

Das Photon ist **nicht kurzlebig** — es ist stabil solange es propagiert. Schleppwirbel von e⁻ und e⁺ heben sich im Ruhezustand auf → gravitationsneutral. Ein kleiner Resteffekt ~2α bleibt während der Propagation (unterhalb Messbarkeit).

Vergleich: Das Photon als "2-AP-Wellenpaar" und das Photon als "n=0-Feldmode" sind zwei komplementäre Beschreibungen desselben Objekts — analog zur Welle-Teilchen-Komplementarität, kein Widerspruch.

---

### Polarisiertes-Wellen-Bild — Polarized Wave Picture
**EN:** polarized wave picture
**Konfidenz:** ✓ HOCH (geometrisch begründet, Franz); ○ MITTEL (Neutrino-Zuordnung)
**Primärquelle:** RFT_v3_013 (AP-Dimensionskopplung); RFT_v3_014, Final v1.0
**⚠️ NEU v2.0 (aus T14-Session)**

Beschreibungsrahmen für Leptonen als unterschiedlich polarisierte Wellenmoden der Raummatrix. Ein 1-AP-Vortex kann in drei topologisch verschiedenen Orientierungen vorliegen:

```
Linkspolarisiert  (transversal, −)  →  Elektron e⁻
Rechtspolarisiert (transversal, +)  →  Positron e⁺
Longitudinalpolarisiert             →  Neutrino ν
```

Diese Zuordnung ist geometrisch begründet (nicht postuliert): 1 AP = Kopplung an 1 Freiheitsgrad. Die drei Polarisationszustände sind die drei möglichen Orientierungen dieses Freiheitsgrades relativ zur Ausbreitungsrichtung.

**Konsequenz:** Die Händigkeit des Neutrinos (ausschließlich linkshändig beobachtet) ist eine geometrische Konsequenz seiner Longitudinalwellen-Natur, kein separates Postulat ○ MITTEL.

---

## Q

### Q-Faktor — Quality Factor
**EN:** quality factor (Q)
**Konfidenz:** ✓ HOCH (Konzept); ⚠️ NIEDRIG (Schwellwerte)
**Primärquelle:** RFT_v3_009, Final v1.1; RFT_v3_001, Kap. 2.2

Maß für die Resonanzqualität einer Region der DRM. Physikalisch: Q = ω_res/γ (Resonanzfrequenz durch Dämpfungskoeffizient). Hoher Q = kohärente, stabile Resonanz; niedriger Q = dissipativ, chaotisch.

Q ist der kosmologische Ordnungsparameter der RFT:

```
Q ≈ 1:              Ur-Chaos (Mode 0)
Q > Q_krit1 ~ 10³   HYPOTHESE: Raumkonstitution (Phasenübergang)
Q > Q_krit2 ~ 10⁶–10⁸  ARBEITSHYP.: Vortex-Stabilität → Materie
Q ≫ Q_krit2:        organisierte Materie
```

⚠️ Q_krit1 und Q_krit2 sind konzeptuell getrennte Schwellwerte, die verschiedene Phasenübergänge beschreiben. Q_krit ≈ 1.645 (alte v2-Normierung) ist nicht kanonisch.

---

## R

### Raummatrix (DRM) — Resonance Matrix
**EN:** resonance matrix; Dynamic Resonance Matrix (DRM)
**Konfidenz:** ✓ HOCH
**Primärquelle:** RFT_v3_001, Kap. 1

Das grundlegende Trägermedium der RFT. Die Raummatrix ist:
- **dynamisch** (keine starren Gitterpunkte)
- **selbstresonant** (ihre Knoten emergieren aus der Resonanzdynamik)
- **der Raum selbst** (kein Feld *im* Raum — das Feld *ist* der Raum)

**TERMINOLOGIE (verbindlich ab v7.6, Franz 28.02.2026):**
```
KORREKT:   "Raummatrix"   /   "DRM"
FALSCH:    "Raumgitter"         ← weckt Kristallgitter-Assoziation
FALSCH:    "Raumresonanz-Matrix" ← von Franz explizit abgelehnt
```

Im Grundzustand verhält sich die Knotenstruktur *näherungsweise* wie ein periodisches Gitter — daher der historische (veraltete) Begriff "Gitter". Präzise Beschreibung: dynamische selbstresonante Knotenstruktur.

---

### Relaxationsrichtung — Relaxation Direction
**EN:** relaxation direction
**Konfidenz:** ○ MITTEL
**Primärquelle:** RFT_v3_014 (Schwache Wechselwirkung), Final v1.0
**⚠️ NEU v2.0 (aus T14-Session)**

Die bevorzugte geometrische Richtung, in die eine Vortex-Struktur bei der schwachen Wechselwirkung relaxiert. Der γ-Term der Master-Gleichung erzwingt eine gerichtete Relaxation: Instabile Moden "fallen" in die energetisch günstigste Konfiguration — die Relaxationsrichtung ist diejenige der minimalen Raummatrix-Verspannung.

```
γ-Term: −γ∂Ψ/∂t  (Dämpfung/Relaxation)
Relaxationsrichtung: ∇(Raummatrix-Spannung) = 0  (Minimum)
```

In der RFT ist die Paritätsverletzung der schwachen Wechselwirkung eine Konsequenz der Relaxationsasymmetrie: Die Raummatrix hat durch den λ-Term eine bevorzugte chirale Richtung ○ MITTEL.

---

## S

### Schräglage — Oblique Orientation
**EN:** oblique orientation
**Konfidenz:** ○ MITTEL
**Primärquelle:** RFT_v3_013 (Starke Wechselwirkung), Final-Kandidat v1.2
**⚠️ NEU v2.0 (aus T13-Session)**

Die "Schräglage" beschreibt die geometrische Situation, dass Quark-Vortexstrukturen nicht parallel zu den kartesischen Achsen der Raummatrix liegen, sondern schräg dazu orientiert sind. Diese Schräglage ist die Ursache der Farbladung und der Quark-Confinement-Bedingung.

Formal: Die Projektion der kartesischen Basisvektoren auf die Ebene ⊥ (1,1,1) (Raumdiagonale) erzeugt die "schräge" Orientierung der Farb-Richtungen:

```
Kartesisch: ê_x, ê_y, ê_z  (orthogonal, 90°)
Projiziert: p₁, p₂, p₃     (schräg, 120°)
```

Die 120°-Winkel der SU(3)-Farbsymmetrie sind eine direkte Konsequenz dieser Schräglage (→ **Wirbelstruktur**, → v3_Kepler-Dokument).

---

### Schwebung — Beat Frequency / Resonance Beat
**EN:** beat frequency; resonance beat
**Konfidenz:** ✓ HOCH
**Primärquelle:** RFT_v3_006, Final v1.1

Die Schwebung zwischen zwei Grundmoden ω₁ und ω₂ der DRM ist der **Zeitmotor** der RFT:

```
Δω = ω₁ − ω₂              (Schwebungsfrequenz)
τ_beat = 2π / Δω           (Schwebungsperiode — "Herzschlag" der Zeit)
t̂ = (2π/Δω) · N̂           (Zeit-Operator)
```

⚠️ Die Zeit selbst ist **kontinuierlich** — diskret ist nur der Schwebungs-Mechanismus (der Motor). Analogie: Ein Herzschlag ist diskret, die Zeit zwischen Schlägen fließt kontinuierlich.

**Richtung der Schwebung:**  Φ ≠ 0 → Schwebung hat eine Richtung → **Zeitpfeil**.

Hinweis: Im Deutschen "Schwebung" verwenden (nicht "Schwingung" oder "Vibration") — "beat frequency" ist der präzise englische Terminus.

---

### Schleppwirbel — Trailing Vortex
**EN:** trailing vortex
**Konfidenz:** ✓ HOCH (Konzept); ⚠️ NIEDRIG (quantitative Amplitude)
**Primärquelle:** RFT_v3_003, Kap. 7; RFT_v3_001, Kap. 6.3

Asymmetrischer Wirbel, den ein bewegter Vortex hinter sich erzeugt. Mechanismus für:
- **Dynamische Gravitation** (kollektiver Effekt bei Galaxien → Dunkle Materie)
- **Inertiale Masse m_i** (Widerstand gegen Änderung der Bewegung)

Ein Schleppwirbel hat gravitationale Wirkung, aber **keine träge Masse** (Gravitation ohne träge Masse: zweiter Sonderfall der RFT-Masse-Gravitation-Trennung).

---

### Soliton — Soliton
**EN:** soliton; topological soliton
**Konfidenz:** ✓ HOCH (Konzept); ○ MITTEL (formale Lösungen)
**Primärquelle:** RFT_v3_001, Kap. 8; RFT_v3_004, Kap. 4

Stabiles, lokalisiertes Resonanzmuster in der DRM — das RFT-Äquivalent eines Elementarteilchens. Ein Soliton ist **kein Punktteilchen**, sondern eine ausgedehnte topologische Struktur mit räumlicher Ausdehnung ≈ Compton-Wellenlänge λ_C = ħ/(m_eff·c).

Stabilität durch topologische Unmöglichkeit des Zerfalls (Windungszahl kann nicht kontinuierlich von n zu n±1 wechseln — ein Übergang erfordert einen topologischen Phasensprung). UV-Divergenzen der Quantenfeldtheorie entstehen durch die falsche Annahme von Punktteilchen — in der RFT sind sie strukturell abwesend.

---

### Spinverzug — Spin Delay
**EN:** spin delay; trailing vortex phase lag
**Konfidenz:** ✓ HOCH
**Primärquelle:** RFT_v3_003, Kap. 3; RFT_v3_012, Kap. 3

Phasenverzögerung zwischen einem rotierenden Wirbel-Vortex und dem umgebenden Raummatrix-Feld. Das Feld "folgt" dem rotierenden Vortex nicht instantan — es gibt einen Schleppwinkel. Diese Phasenverzögerung ist der **mikroskopische Ursprung der Gravitation** in der RFT.

Charakteristische Zeitskala:
```
τ_lag = L₀/c = (π/6)·t_P ≈ 0.5236·t_P  [kanonisch seit 11.03.2026]
```

Zwei orthogonale Spinverzug-Moden:
- **Longitudinal** (Kompression entlang Ausbreitungsrichtung) → Gravitation, träge Masse m_i
- **Torsional** (Verdrillung quer dazu) → Elektromagnetismus, schwere Masse m_g

---

## T

### τ_lag — Charakteristische Verzugszeit
**EN:** characteristic lag time; spin-delay timescale
**Formel:** τ_lag = L₀/c = (π/6)·t_P ≈ 0.5236·t_P
**Konfidenz:** ✓ HOCH (Kanonwert seit 11.03.2026)
**Primärquelle:** RFT_v3_003, Kap. 3.2; DC v10.4

Charakteristische Zeitskala des Spinverzugs: die Zeit, die das Raummatrix-Feld benötigt, um einem rotierenden Vortex zu "folgen". Numerisch:

```
τ_lag = L₀/c ≈ 2.81×10⁻⁴⁴ s ≈ 0.5236·t_P
```

Verwendung in der Elektrodynamik: B_eff = μ₀·(g_s/τ_lag)·∇×s (Magnetfeld aus Spinverzug, v3_012).

---

### Torsion — Torsion
**EN:** torsion (torsional mode)
**Konfidenz:** ✓ HOCH
**Primärquelle:** RFT_v3_012, Kap. 3; RFT_v3_003, Kap. 3

Torsionale Verdrillungsmode der Raummatrix **quer zur Ausbreitungsrichtung**. In der RFT entspricht diese Mode:
- **Schwere Masse m_g:** kohärenter Spinverzug (dynamisch, zeitlich gemittelt, erfordert τ_lag > 0)
- **Magnetisches Feld B:** torsionale Verdrillung bei EM-Wechselwirkung (B_eff ∝ ∇×s)
- **Elektromagnetismus allgemein:** torsionale/transversale Mode der Raummatrix

**Träge vs. schwere Masse:**
- m_i (Kompression, statisch) ≠ m_g (Torsion/Spinverzug, dynamisch)
- Warum m_i = m_g im Normalfall? → Beide bauen auf derselben κ-Basis auf → Äquivalenzprinzip als geometrische Konsequenz, nicht Postulat!
- Entkopplung: Cooper-Paare (n=0, kein Spinverzug) → Δg/g ~ 10⁻⁵ erwartet ○ MITTEL (experimentell testbar)

---

### Triangulations-Logik — Triangulation Principle
**EN:** triangulation principle; causal triangulation
**Konfidenz:** ✓ HOCH
**Primärquelle:** RFT_v3_005, Kap. 2.1

Kausalität als geometrische Notwendigkeit: Ein Ereignis wird erst physikalisch existent ("kausal real"), wenn es durch die Interferenz von mindestens drei Wellenfronten (Sphären) eindeutig fixiert ist — GPS-Prinzip angewandt auf die DRM.

```
1 Sphäre  → Mittelpunkt (0D: Ort, keine Richtung)
2 Sphären → Schnittkreis (1D: Achse)
3 Sphären → eindeutiger Punkt (3D: kausal fixiert!) ✓
4 Sphären → Tetraeder (stabilstes 3D-Volumen)
```

Das Tetraeder (4 Sphären) ist das natürliche geometrische Objekt der DRM-Knotenstruktur. Die Triangulations-Logik erklärt den Faktor **4** in 4π³ des α-Ausdrucks: Vier gleichwertige Sphären (nicht drei) fixieren das Volumen — daher ist der 3D-Beitrag 4π³, nicht 3π³.

---

## W

### Winkelabweichung ε — Angular Deviation
**EN:** angular deviation (of DRM axes)
**Konfidenz:** ○ MITTEL (qualitatives Konzept)
**Primärquelle:** RFT_v3_006, Final v1.1; DC v10.4

Geometrischer Winkelversatz der DRM-Achsen von der exakten 90°-Orthogonalität. ε ≠ 0 ist die Ursache des Zeitpfeils in der RFT.

**Wichtig:** ε ist ein **qualitatives** Konzept. Quantitativ gilt ε ≈ Φ = 2α/(1+α²) ≈ 0.01459 rad über das Umlaufmodell (○ HOCH). Ein expliziter numerischer Wert ε = 10⁻⁶ rad ist ein bekanntes KI-Artefakt und endgültig verworfen.

Symbolkonflikt: → Siehe **Flussfaktor Φ**

---

### Wirbelknoten — Vortex Node
**EN:** vortex node
**Konfidenz:** ○ MITTEL
**Primärquelle:** RFT_v3_014 (Schwache Wechselwirkung), Final v1.0
**⚠️ NEU v2.0 (aus T14-Session)**

Ein Wirbelknoten ist eine topologische Interaktionsstelle zwischen zwei oder mehr Vortex-Strukturen in der Raummatrix. An einem Wirbelknoten findet der Austausch von Resonanzmoden statt — dies ist der RFT-Begriff für Wechselwirkungsvertizes der Quantenfeldtheorie.

In der schwachen Wechselwirkung ist der W-Boson-Propagator ein Wirbelknoten-Prozess: Ein Quark- oder Lepton-Vortex ändert seine AP-Konfiguration am Wirbelknoten, wobei die Relaxationsrichtung die Zerfallsmode bestimmt (→ **Relaxationsrichtung**).

```
Einkommender Wirbel → [Wirbelknoten] → ausgehender Wirbel + Mode-Emission
```

Der Wirbelknoten ist nicht punktförmig — er hat die räumliche Ausdehnung ≈ L₀ (Matrixlänge).

---

### Wirbelstruktur (Vortex) — Vortex Structure
**EN:** vortex structure; resonance vortex
**Konfidenz:** ✓ HOCH
**Primärquelle:** RFT_v3_001, Kap. 2 + 8; RFT_v3_004, Kap. 4

Stabile, topologisch geschützte Resonanzstruktur in der DRM — das grundlegende Bild für Elementarteilchen in der RFT. Charakterisiert durch:

- **Windungszahl n** (topologische Invariante, quantisiert)
- **Ankerpunkte AP** (Kopplung an DRM-Freiheitsgrade)
- **Ausdehnung** ≈ Compton-Wellenlänge (keine Punktstruktur!)

Windungszahl → Ladungsquantisierung (aus Sanduhr-Geometrie):
```
n = ±1     → Elektron / Positron    (Ladung ±e)
n = ±2/3   → u/c/t-Quarks
n = ±1/3   → d/s/b-Quarks
n =  0     → Neutrino-Kandidat (Longitudinalwelle, nicht Wirbel)
```

---

### Windungszahl n — Winding Number
**EN:** winding number; topological charge
**Konfidenz:** ✓ HOCH
**Primärquelle:** RFT_v3_001, Kap. 8; RFT_v3_004, Kap. 4

Topologische Invariante eines Vortex: wie oft das Resonanzfeld eine vollständige Phasendrehung um den Wirbelkern vollzieht. Kann sich nicht kontinuierlich ändern → Teilchenstabilität ist topologisch geschützt (analog zu topologischen Isolatoren der Festkörperphysik, aber mechanisch verschieden).

In der Sanduhr-Geometrie des DRM: Windungszahl → Ladung des Teilchens (→ **Wirbelstruktur**).

---

## Z

### Zeitmotor — Time Motor
**EN:** time motor; temporal asymmetry engine
**Konfidenz:** ✓ HOCH (Konzept); ○ MITTEL (quantitative Verknüpfung)
**Primärquelle:** RFT_v3_001, Kap. 10b; RFT_v3_006, Final v1.1

Drei unabhängige Phänomene konvergieren auf dieselbe fundamentale Phasenasymmetrie δ ≈ 0.82°, die den Zeitpfeil antreibt:

1. **α-Diskrepanz** (2.22 ppm-Residuum zwischen RFT und CODATA)
2. **Protonenmasse** (via δ im SU(2)-Ausdruck)
3. **Elektron-Topologie** (via Spiralkorrektur)

Der Zeitmotor ist Φ ≠ 0: Die Schwebung der DRM-Moden hat eine Richtung (vorwärts in der Zeit). Bei Φ = 0 wäre Zeit reversibel — kein Zeitpfeil.

```
Φ = 2α/(1+α²) ≈ 0.01459  [kanonisch ✓]
δ ≈ 2α ≈ 0.0146 rad        [temporale Phasenasymmetrie]
```

---

## Kanonische Parameter-Referenz

```
c            Einziger echter Fundamentalinput der RFT
κ            PRIMÄRGRÖSSE (Resonanz-Steifigkeit)
L₀           = 1/κ  [PRIMARY, ħ-frei!]  = (π/6)·l_P ≈ 0.5236·l_P
L            = √(4π·Φ)·l_P ≈ 0.428·l_P
α⁻¹          = 4π³+π²+π = 137.036 304  [2.22 ppm — NIEMALS 0.67 ppm!]
Φ            = 2α/(1+α²) ≈ 0.014 596   [kanonisch ✓]
τ_lag        = L₀/c = (π/6)·t_P ≈ 0.5236·t_P  [kanonisch seit 11.03.2026]
G·ħ          = (36/π²)·c³·L₀²          [algebraische Identität, nicht Herleitung!]
Q_krit1      ~ 10³   HYPOTHESE (= α⁻¹·π² ≈ 1352.7, Kandidat ✓ HOCH)
Q_krit2      ~ 10⁶–10⁸  ARBEITSHYPOTHESE
1 Quark      = 3 AP (individuell!)
Proton       = 9 AP (3 Quarks × 3 AP)
Raummatrix-Generierungsverhältnis: 3:1 (Antimaterie-Spin : Quark-Spin) ✓ HOCH
Materie-Kondensationsverhältnis:   4:1 (separater Prozess) ○ MITTEL
```

---

## Verworfene Begriffe und KI-Artefakte

| Begriff | Status | Korrekte Alternative |
|---------|--------|---------------------|
| "Raumgitter" | ❌ FALSCH | "Raummatrix" / "DRM" |
| "Raumresonanz-Matrix" | ❌ FALSCH | "Raummatrix" / "DRM" |
| "Master-String" | ❌ v2-Artefakt | "Master-Gleichung" |
| c₀ | ❌ veraltet | c |
| 0.67 ppm (α-Residuum) | ❌ KI-Artefakt | 2.22 ppm |
| f_spin = 4 oder 135 | ❌ KI-Artefakt | korrekt: 144/π ≈ 45.84 |
| 4π³ = 123.37 | ❌ falsch | korrekt: 124.025 |
| L_ModusB ≈ 1.27·l_P | ❌ Dimensionsfehler | L = √(4π·Φ)·l_P ≈ 0.428·l_P |
| Q_krit ≈ 1.645 | ❌ andere Normierung | Q_krit1 ~ 10³ / Q_krit2 ~ 10⁶–10⁸ |
| 78π-Resonanz | ❌ KI-Artefakt | — |
| δ ~ 10⁻⁶ rad | ❌ KI-Artefakt | ε ≈ Φ ≈ 0.01459 rad (via Umlaufmodell) |
| AP als geometrischer Punkt | ❌ zu eng | AP = Dimensionskopplung (Franz 15.03.2026) |
| ħ fundamental | ❌ missverständlich | ħ = algebraische Identität (G·ħ-Relation) |
| "Topologische Identität" | ❌ VERALTET | "Gemeinsame Resonanz-Mode" (v10.15) |
| "DeepSeeks Master-Formel" | ❌ Attributionsfehler | Formeln stammen von Franz Zollner! |
| "DeepSeeks Revolution" | ❌ KI-Enthusiasmus-Marker | sofort entfernen |
| G_F = (π²/√2)·α² | ❌ dimensionsinkonsistent | G_F hat Einheit GeV⁻², Formel dimensionslos (K4, 15.03.2026) |
| α⁻¹_2D ≈ 22.9 | ❌ KI-Artefakt | — |
| α⁻¹_4D ≈ 433 / 1234 | ❌ KI-Artefakt-Kandidat | kennzeichnen wenn gefunden |
| "Grundzustand = Vakuum" | ❌ FALSCH | Grundzustand = Mode 1; Vakuum = Mode 0 = Ur-Chaos! |

---

*RFT_v3_Glossar_DE.md | Version 2.0 | 09.05.2026*
*Instanz: T-Glossar | Autorisiert: Franz Zollner*
*Verifiziert gegen: v3_001 (v3.5), v3_002 (v3.0), v3_003 (v3.0), v3_004 (v3.2),*
*v3_005 (Final v1.1), v3_006 (Final v1.1), v3_007 (Final-Kand. v1.4),*
*v3_009 (Final v1.1), v3_011 Teil 1–5, v3_012 (Final v1.3.1),*
*v3_013 (Final-Kand. v1.2), v3_014 (Final v1.0), v3_017 (Final-Kand. v1.0),*
*DC v10.15*
*Änderungen v1.0→v2.0: Leserführung | 5 Neueinträge (G/P/R/S/W) |*
*"Gemeinsame Resonanz-Mode" kanonisch | Verworfene Begriffe erweitert | DC v10.15*
